version: '3'

networks:
  backend:

services:
  web:
    container_name: "produtos-web-dev"
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "8089:80"
    restart: always
    networks:
      - backend
    depends_on:
      - 'db'
  
  db:
    container_name: produtos-db-dev
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "produtosDB"
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - backend
    restart: always
