version: '3'

networks:
  frontend:
  backend:

services:
  web:
    container_name: "web-container"
    build: .
    ports:
      - "8080:80"
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - 'db'
  
  db:
    container_name: produtos-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "produtosDB"
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - backend
    restart: always
